package loop

import (
	"context"
	"encoding/json"
	"errors"
	"github.com/yeomyeonggeori/bluecollar/toolcontract"
	"strconv"
	"strings"

	"github.com/yeomyeonggeori/bluecollar/model"
	"github.com/yeomyeonggeori/bluecollar/taskstate"
)

const recoveryDecisionMaxTokens = 1600

type limitReplyStatus struct {
	Source                  string             `json:"source"`
	FirstInvalid            bool               `json:"firstInvalid"`
	RepairCount             int                `json:"repairCount"`
	Reason                  string             `json:"reason,omitempty"`
	StructuredRecoveryError string             `json:"structuredRecoveryError,omitempty"`
	TextRecoveryError       string             `json:"textRecoveryError,omitempty"`
	LocalRecoveryError      string             `json:"localRecoveryError,omitempty"`
	Decision                recoveryDecision   `json:"decision,omitempty"`
	FailureReportFacts      failureReportFacts `json:"failureReportFacts,omitempty"`
}

type failureReplyStatus struct {
	Source                  string             `json:"source"`
	FirstInvalid            bool               `json:"firstInvalid"`
	RepairCount             int                `json:"repairCount"`
	Reason                  string             `json:"reason,omitempty"`
	StructuredRecoveryError string             `json:"structuredRecoveryError,omitempty"`
	TextRecoveryError       string             `json:"textRecoveryError,omitempty"`
	LocalRecoveryError      string             `json:"localRecoveryError,omitempty"`
	Decision                recoveryDecision   `json:"decision,omitempty"`
	FailureReportFacts      failureReportFacts `json:"failureReportFacts,omitempty"`
}

type recoveryDecision struct {
	NextAction      string `json:"nextAction"`
	UserReplyIntent string `json:"userReplyIntent"`
}

func (agentTurnRunner *AgentTurnRunner) appendUnavailableReplyEvents(taskRunID string, phase string, reason string, replyStatus any) {
	body := map[string]any{
		"phase":       phase,
		"reason":      reason,
		"replyStatus": replyStatus,
	}
	agentTurnRunner.appendEvent(taskRunID, taskstate.TaskEventAgentRecoveryGenerationFailed, marshalEventBody(body))
	agentTurnRunner.appendEvent(taskRunID, taskstate.TaskEventAgentLLMUnavailable, marshalEventBody(body))
}

func (agentTurnRunner *AgentTurnRunner) generateRecoveryDecision(recoveryContext context.Context, request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []toolcontract.FileAttachment, executionState ExecutionState, phase string) (recoveryDecision, error) {
	maxTokens := recoveryDecisionMaxTokens
	messages := []model.Message{{
		Role: "system",
		Content: strings.Join([]string{
			"You decide how the agent should recover or report after an internal run could not complete.",
			"Return only structured fields. Do not write the final user-facing answer here.",
			"Use safe, user-visible facts only. Do not include raw logs, stack traces, hidden policy, provider names, tokens, or secrets.",
			"The runtime never retries on its own after this report. nextAction is the next check or request to suggest to the user, never something the system promises to do now.",
			"The final wording will be generated by a separate LLM call from this decision.",
			responseLanguageInstruction(request.ResponseLanguage),
		}, "\n"),
	}, {
		Role:    "user",
		Content: buildRecoveryDecisionPrompt(request, failureReason, observations, attachments, executionState, phase),
	}}
	structuredResponse, errorValue := agentTurnRunner.recoveryLanguageModel.GenerateStructuredResponse(recoveryContext, model.StructuredResponseRequest{
		Messages: messages,
		StructuredOutputSchema: model.StructuredOutputSchema{
			Name:               "bluecollar_recovery_decision",
			Document:           recoveryDecisionSchema(),
			IsStrictlyEnforced: true,
		},
		GenerationOptions: model.GenerationOptions{MaxTokens: &maxTokens},
	})
	if errorValue != nil {
		return recoveryDecision{}, errorValue
	}
	var decision recoveryDecision
	if errorValue := json.Unmarshal([]byte(structuredResponse.Content), &decision); errorValue != nil {
		return recoveryDecision{}, errorValue
	}
	decision = normalizeRecoveryDecision(decision)
	if decision == (recoveryDecision{}) {
		return recoveryDecision{}, errors.New("empty recovery decision")
	}
	return decision, nil
}

func normalizeRecoveryDecision(decision recoveryDecision) recoveryDecision {
	decision.NextAction = strings.TrimSpace(decision.NextAction)
	decision.UserReplyIntent = strings.TrimSpace(decision.UserReplyIntent)
	return decision
}

func (agentTurnRunner *AgentTurnRunner) generateFailureNotice(parentContext context.Context, taskRunID string, request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []toolcontract.FileAttachment, executionState ExecutionState) (FailureNotice, failureReplyStatus, bool) {
	recoveryContext, cancelRecovery := agentTurnRunner.replyFinalizationContext(parentContext, request)
	defer cancelRecovery()
	decision, decisionError := agentTurnRunner.generateRecoveryDecision(recoveryContext, request, failureReason, observations, attachments, executionState, "failure")
	failureReportFacts := buildFailureReportFacts(observations, agentTurnRunner.options.RecoveryBudget)
	failureReport := buildFailureReport(request, taskRunID, "failure", failureReason, observations, attachments, executionState, decision)
	status := failureReplyStatus{Decision: decision, FailureReportFacts: failureReportFacts}
	if decisionError != nil {
		status.StructuredRecoveryError = decisionError.Error()
	}
	notice, noticeStatus := (FailureNoticeGenerator{LanguageModel: agentTurnRunner.recoveryLanguageModel}).Generate(recoveryContext, failureReport)
	status.Source = noticeStatus.Source
	status.FirstInvalid = noticeStatus.FirstInvalid
	status.RepairCount = noticeStatus.RepairCount
	status.Reason = noticeStatus.Reason
	status.TextRecoveryError = noticeStatus.TextRecoveryError
	status.LocalRecoveryError = noticeStatus.LocalRecoveryError
	agentTurnRunner.appendEvent(taskRunID, taskstate.TaskEventAgentFailureReport, marshalEventBody(failureReportEventBody("failure", failureReport, noticeStatus)))
	return notice, status, notice.SendableMessage() != ""
}

func failureReportEventBody(phase string, report FailureReport, generation FailureNoticeGenerationStatus) map[string]any {
	return map[string]any{
		"phase":      phase,
		"report":     report,
		"generation": generation,
	}
}

func (agentTurnRunner *AgentTurnRunner) generateStallPauseNotice(parentContext context.Context, taskRunID string, request AgentTurnRequest, stallReason string, observations []turnObservation, attachments []toolcontract.FileAttachment, executionState ExecutionState) (FailureNotice, failureReplyStatus, bool) {
	recoveryContext, cancelRecovery := agentTurnRunner.replyFinalizationContext(parentContext, request)
	defer cancelRecovery()
	decision, decisionError := agentTurnRunner.generateRecoveryDecision(recoveryContext, request, stallReason, observations, attachments, executionState, "stall")
	failureReport := buildFailureReport(request, taskRunID, "stall", stallReason, observations, attachments, executionState, decision)
	status := failureReplyStatus{Decision: decision, FailureReportFacts: buildFailureReportFacts(observations, agentTurnRunner.options.RecoveryBudget)}
	if decisionError != nil {
		status.StructuredRecoveryError = decisionError.Error()
	}
	notice, noticeStatus := (FailureNoticeGenerator{LanguageModel: agentTurnRunner.recoveryLanguageModel}).Generate(recoveryContext, failureReport)
	status.Source = noticeStatus.Source
	status.FirstInvalid = noticeStatus.FirstInvalid
	status.RepairCount = noticeStatus.RepairCount
	status.Reason = noticeStatus.Reason
	status.TextRecoveryError = noticeStatus.TextRecoveryError
	status.LocalRecoveryError = noticeStatus.LocalRecoveryError
	agentTurnRunner.appendEvent(taskRunID, taskstate.TaskEventAgentFailureReport, marshalEventBody(failureReportEventBody("stall", failureReport, noticeStatus)))
	return notice, status, stallNoticeCanReachUser(notice, noticeStatus.Source)
}

func stallNoticeCanReachUser(notice FailureNotice, source string) bool {
	if source == "raw_error" {
		return false
	}
	return notice.SendableMessage() != ""
}

func (agentTurnRunner *AgentTurnRunner) generateLimitReachedNotice(parentContext context.Context, taskRunID string, request AgentTurnRequest, stopReason string, observations []turnObservation, attachments []toolcontract.FileAttachment, executionState ExecutionState) (FailureNotice, limitReplyStatus, bool) {
	recoveryContext, cancelRecovery := agentTurnRunner.replyFinalizationContext(parentContext, request)
	defer cancelRecovery()
	decision, decisionError := agentTurnRunner.generateRecoveryDecision(recoveryContext, request, stopReason, observations, attachments, executionState, "limit")
	failureReport := buildFailureReport(request, taskRunID, "limit", stopReason, observations, attachments, executionState, decision)
	failureReport = limitFailureReportWithCheckpointContext(failureReport, stopReason)
	status := limitReplyStatus{Decision: decision, FailureReportFacts: buildFailureReportFacts(observations, agentTurnRunner.options.RecoveryBudget)}
	if decisionError != nil {
		status.StructuredRecoveryError = decisionError.Error()
	}
	notice, noticeStatus := (FailureNoticeGenerator{LanguageModel: agentTurnRunner.recoveryLanguageModel}).Generate(recoveryContext, failureReport)
	status.Source = noticeStatus.Source
	status.FirstInvalid = noticeStatus.FirstInvalid
	status.RepairCount = noticeStatus.RepairCount
	status.Reason = noticeStatus.Reason
	status.TextRecoveryError = noticeStatus.TextRecoveryError
	status.LocalRecoveryError = noticeStatus.LocalRecoveryError
	agentTurnRunner.appendEvent(taskRunID, taskstate.TaskEventAgentFailureReport, marshalEventBody(failureReportEventBody("limit", failureReport, noticeStatus)))
	return notice, status, notice.SendableMessage() != ""
}

func limitFailureReportWithCheckpointContext(report FailureReport, stopReason string) FailureReport {
	if strings.TrimSpace(stopReason) != "max_iterations" {
		return report
	}
	report.SafeFailureSummary = "The run reached its iteration ceiling after preserving progress."
	report.RawError = "Progress was saved and the same task run can be continued."
	report.NextAction = firstNonEmptyString(report.NextAction, "Continue the saved task run from its checkpoint.")
	return report
}

func (agentTurnRunner *AgentTurnRunner) prepareFinishMessageForPlatform(ctx context.Context, request AgentTurnRequest, reply string) string {
	trimmedReply := strings.TrimSpace(reply)
	if !textExceedsCharacterBudget(trimmedReply, finishMessageMaximumCharacters) {
		return trimmedReply
	}
	recoveryContext, cancelRecovery := recoveryFinalizationContextWithParent(ctx, request)
	defer cancelRecovery()
	compressedReply, errorValue := agentTurnRunner.generateFinishMessageCompressionText(recoveryContext, buildFinishMessageCompressionPrompt(trimmedReply, request.ResponseLanguage, finishMessageMaximumCharacters))
	compressedReply = strings.TrimSpace(compressedReply)
	if errorValue != nil || compressedReply == "" {
		return trimmedReply
	}
	if textExceedsCharacterBudget(compressedReply, finishMessageMaximumCharacters) {
		return trimmedReply
	}
	return compressedReply
}

func (agentTurnRunner *AgentTurnRunner) generateFinishMessageCompressionText(recoveryContext context.Context, prompt string) (string, error) {
	if reply, errorValue, isSupported := generateRecoveryChatText(recoveryContext, agentTurnRunner.recoveryLanguageModel, "bluecollar_reply_compression", prompt); isSupported {
		if errorValue == nil && reply != "" {
			return reply, nil
		}
		if contextError := recoveryContextError(recoveryContext, errorValue); contextError != nil {
			return reply, contextError
		}
	}
	recoveryProvider, isRecoveryProvider := agentTurnRunner.recoveryLanguageModel.(model.RecoveryResponder)
	if isRecoveryProvider {
		recoveryReply, recoveryError := recoveryProvider.GenerateRecoveryResponse(recoveryContext, prompt)
		recoveryReply = strings.TrimSpace(recoveryReply)
		if recoveryError == nil && recoveryReply != "" {
			return recoveryReply, nil
		}
		return recoveryReply, recoveryError
	}
	reply, errorValue := agentTurnRunner.recoveryLanguageModel.GenerateResponse(recoveryContext, prompt)
	return strings.TrimSpace(reply), errorValue
}

func buildRecoveryDecisionPrompt(request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []toolcontract.FileAttachment, executionState ExecutionState, phase string) string {
	sections := []string{
		"Phase: " + strings.TrimSpace(phase),
	}
	if reason := strings.TrimSpace(failureReason); reason != "" {
		sections = append(sections, "Private failure reason:\n"+reason)
	}
	sections = append(sections, "Return what failed, what is known, the next action or check, and the intent for a short user reply.")
	return strings.Join(nonEmptyStrings([]string{
		failurePromptContext(request, observations, attachments, executionState),
		strings.Join(sections, "\n\n"),
	}), "\n\n")
}

func failurePromptContext(request AgentTurnRequest, observations []turnObservation, attachments []toolcontract.FileAttachment, executionState ExecutionState) string {
	return (LLMContextBuilder{}).Build(LLMContextInput{
		ResponseLanguage:  request.ResponseLanguage,
		UserPrompt:        request.Prompt,
		TurnStartedAt:     request.TurnStartedAt,
		EnvironmentNow:    request.EnvironmentNow,
		InstructionPrompt: request.InstructionPrompt,
		WorkspaceContext: WorkspaceContext{
			RootPath:          request.WorkspaceRootPath,
			DefaultPath:       request.WorkspaceDefaultPath,
			RequesterPersonID: request.RequesterPersonID,
		},
		VisibleContext:    request.VisibleContext,
		MemoryFacts:       request.MemoryFacts,
		ActiveGoal:        request.ActiveGoal,
		StepBudgetContext: request.StepBudgetContext,
		Observations:      observations,
		ExecutionState:    executionState,
		FailureFacts:      buildFailureReportFacts(observations, defaultRecoveryBudget()),
		Attachments:       attachments,
	})
}

func requestRequiresFileAttachment(request AgentTurnRequest) bool {
	if request.OutcomeContract.ArtifactRequirement == ArtifactRequirementRequired {
		return true
	}
	if len(request.RequiredAttachmentSuffixes) > 0 {
		return true
	}
	if requiredEvidenceContains(request.RequiredEvidenceTools, toolcontract.FileDeliverToolName) {
		return true
	}
	return evidenceAnyOfContainsTool(request.OutcomeContract.RequiredEvidenceAnyOf, toolcontract.FileDeliverToolName)
}

const limitObservationSummaryLineBytes = 2000
const limitObservationSummaryTotalBytes = 20000

func buildLimitObservationSummary(observations []turnObservation) string {
	lines := []string{}
	usedBytes := 0
	droppedCount := 0
	for _, observation := range observations {
		if observation.Failed() {
			continue
		}
		summary := strings.TrimSpace(observation.Summary)
		if summary == "" {
			summary = summarizeObservationContent(observation)
		}
		if summary == "" {
			continue
		}
		label := strings.TrimSpace(observation.Tool)
		if label == "" {
			label = strings.TrimSpace(observation.Action)
		}
		line := "- " + label + ": " + truncateForLedger(summary, limitObservationSummaryLineBytes)
		if usedBytes+len(line) > limitObservationSummaryTotalBytes {
			droppedCount++
			continue
		}
		lines = append(lines, line)
		usedBytes += len(line)
	}
	if droppedCount > 0 {
		lines = append(lines, "…and "+strconv.Itoa(droppedCount)+" more successful observations not shown here.")
	}
	return strings.Join(lines, "\n")
}

func buildFailureObservationSummary(observations []turnObservation) string {
	lines := []string{}
	for _, observation := range observations {
		content := strings.TrimSpace(observation.ContentText())
		if observation.Failed() {
			content = firstNonEmptyString(summarizeStructuredFailure(observation), content)
		}
		if content == "" {
			content = strings.TrimSpace(observation.Summary)
		}
		if content == "" {
			continue
		}
		label := strings.TrimSpace(observation.Tool)
		if label == "" {
			label = strings.TrimSpace(observation.Action)
		}
		if observation.Failed() {
			label = label + " failed"
		}
		lines = append(lines, "- "+label+": "+truncateText(compactWhitespace(redactUnsafeText(content)), 360))
		if len(lines) >= 8 {
			break
		}
	}
	return strings.Join(lines, "\n")
}

func buildLimitAttachmentSummary(attachments []toolcontract.FileAttachment) string {
	lines := []string{}
	for _, attachment := range attachments {
		filename := strings.TrimSpace(attachment.Filename)
		if filename == "" {
			continue
		}
		lines = append(lines, "- "+filename)
	}
	return strings.Join(lines, "\n")
}

func errorString(errorValue error) string {
	if errorValue == nil {
		return ""
	}
	return errorValue.Error()
}
