package loop

import (
	"encoding/json"
	"os"
	"testing"
)

// Where these two documents came from, in the only place that cannot rot: a
// test that fails when the copy stops looking like what it was copied from.
//
// protocol-fixtures.json is blueclaw's protocol/fixtures/valid.json, and
// blueclaw's TestHarnessTestdataMatchesProtocolSource holds the two byte for
// byte.
//
// capability-tools.json is a product's tool catalog, generated by internkim
// into pkg/capabilityprotocol/generated/capability-tools.json. Nothing holds
// this copy to it, and nothing should: the loop needs eight tools with real
// schemas to exercise action shaping, and it does not care whose tools they
// are. Refresh it by hand when a richer sample is wanted.
const capabilityCatalogFixtureSource = "internkim pkg/capabilityprotocol/generated/capability-tools.json"

func TestTheCapabilityCatalogFixtureStillCarriesTheToolsTheLoopShapesActionsFor(t *testing.T) {
	document, errorValue := os.ReadFile("testdata/capability-tools.json")
	if errorValue != nil {
		t.Fatalf("the capability catalog fixture, copied from %s, is unreadable: %v", capabilityCatalogFixtureSource, errorValue)
	}
	var catalog struct {
		ProtocolVersion string `json:"protocolVersion"`
		Tools           []struct {
			ModelName   string          `json:"modelName"`
			Description string          `json:"description"`
			InputSchema json.RawMessage `json:"inputSchema"`
		} `json:"tools"`
	}
	if errorValue := json.Unmarshal(document, &catalog); errorValue != nil {
		t.Fatalf("the capability catalog fixture, copied from %s, is not a catalog: %v", capabilityCatalogFixtureSource, errorValue)
	}
	if catalog.ProtocolVersion == "" {
		t.Errorf("the capability catalog fixture names no protocol version")
	}

	carried := map[string]bool{}
	for _, tool := range catalog.Tools {
		if tool.Description == "" || len(tool.InputSchema) == 0 {
			t.Errorf("%s carries no description or input schema, so it shapes no action", tool.ModelName)
		}
		carried[tool.ModelName] = true
	}
	for _, toolName := range []string{
		"task_add", "task_update", "message_send", "message_search",
		"document_read", "image_read", "web_search", "site_serve",
	} {
		if !carried[toolName] {
			t.Errorf("%s is gone from the fixture; refresh it from %s", toolName, capabilityCatalogFixtureSource)
		}
	}
}
